# -*- coding: utf-8 -*-
# 1.install python 3-anaconda
# >ANACONDA_VERSION=5.1.0
# >curl -L https://repo.continuum.io/archive/Anaconda3-${ANACONDA_VERSION}-Linux-x86_64.sh -o Anaconda3-${ANACONDA_VERSION}-Linux-x86_64.sh
# >/bin/bash Anaconda3-${ANACONDA_VERSION}-Linux-x86_64.sh -b -p /opt/anaconda
# >vi /etc/profile
# at the end of file, append
# PATH="/opt/anaconda/bin:${PATH}"
# export PATH
# ESC  ->  wq   ->
# >source /etc/profile
# >export $PATH
# 2. refence python to anaconda
# >mv /usr/bin/python /usr/bin/python_old
# >ln -s /opt/anaconda/bin/python /usr/bin/python
# > vi /usr/bin/yum
# > modify the first line: #!/usr/bin/python    ------>  #!/usr/bin/python_old
# 3. install pip
# (centos)>yum -y install python-pip
# (ubuntu)>apt-get install python-pip
# (centos)
# #install setup tools
# >curl https://bitbucket.org/pypa/setuptools/downloads/ez_setup.py | python -
# #install pip
# >curl https://bootstrap.pypa.io/get-pip.py | python -
# 3. install docker-compose
# Note that Compose 1.5.2 requires Docker 1.7.1 or later
# docker --version
# pip uninstall docker-compose
# pip install docker-compose==1.5.2
# 4. runging the applicaiton
# >docker-compose up -d -f xxx.yml
# OR
# >docker-compose up    =>running in forground
# docker-compose ps
# docker-compose logs
# docker-compose stop
# docker-compose restart
# 5. docker exec -it container_id /bin/bash
# docker start container_id
app:
   image: shuixin536/docker-pasc
   ports:
      - "5900:5900"
      - "18000:8000"
   # auto add record in /etc/hosts
   # 172.17.2.186  mysqldb
   links:
       - mysqldb
   #command: /bin/bash
   tty: true
nginx-proxy:
   image: jwilder/nginx-proxy
   container_name: nginx-proxy
   ports:
    - "10080:80"
    - "10443:443"
   links:
       - app
   volumes:
     - /root/docker-data/nginx/conf.d/webotc.conf:/etc/nginx/conf.d/webotc.conf:ro
     - /root/docker-data:/data
     - /var/run/docker.sock:/tmp/docker.sock:ro
mysqldb:
   image: centurylink/mysql
   ports:
       # same as "docker run -p"
       - "13306:3306"
   environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: bitdreams
       MYSQL_USER: root
       MYSQL_PASSWORD: root
     