version: '2'
services:
 app:
     image: shuixin536/pasc
     ports:
        - "10022:22"
     links:
         - mysqldb
     environment:
         DB_HOST: db
         DB_DATABASE: laravel
         DB_USERNAME: root
         DB_PASSWORD: root
 mysqldb:
     image: centurylink/mysql
     ports:
         - "13306:3306"
     environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: bitdreams
         MYSQL_USER: root
         MYSQL_PASSWORD: root